/* soapServer.c
   Generated by gSOAP 2.8.17r from zonekey_sysmgrt.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.17r 2014-02-06 23:52:54 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "zkreg:regHost"))
		return soap_serve_zkreg__regHost(soap);
	if (!soap_match_tag(soap, soap->tag, "zkreg:unregHost"))
		return soap_serve_zkreg__unregHost(soap);
	if (!soap_match_tag(soap, soap->tag, "zkreg:regService"))
		return soap_serve_zkreg__regService(soap);
	if (!soap_match_tag(soap, soap->tag, "zkreg:unregService"))
		return soap_serve_zkreg__unregService(soap);
	if (!soap_match_tag(soap, soap->tag, "zkreg:regDevice"))
		return soap_serve_zkreg__regDevice(soap);
	if (!soap_match_tag(soap, soap->tag, "zkreg:unregDevice"))
		return soap_serve_zkreg__unregDevice(soap);
	if (!soap_match_tag(soap, soap->tag, "zkreg:heartBeat"))
		return soap_serve_zkreg__heartBeat(soap);
	if (!soap_match_tag(soap, soap->tag, "zkreg:setShowName"))
		return soap_serve_zkreg__setShowName(soap);
	if (!soap_match_tag(soap, soap->tag, "zkq:getAllMses"))
		return soap_serve_zkq__getAllMses(soap);
	if (!soap_match_tag(soap, soap->tag, "zkq:getAllHosts"))
		return soap_serve_zkq__getAllHosts(soap);
	if (!soap_match_tag(soap, soap->tag, "zkq:getAllServices"))
		return soap_serve_zkq__getAllServices(soap);
	if (!soap_match_tag(soap, soap->tag, "zkq:getAllDevices"))
		return soap_serve_zkq__getAllDevices(soap);
	if (!soap_match_tag(soap, soap->tag, "zkq:getAllLogics"))
		return soap_serve_zkq__getAllLogics(soap);
	if (!soap_match_tag(soap, soap->tag, "zkq:getServicesByType"))
		return soap_serve_zkq__getServicesByType(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkreg__regHost(struct soap *soap)
{	struct zkreg__regHost soap_tmp_zkreg__regHost;
	struct zkreg__regHostResponse soap_tmp_zkreg__regHostResponse;
	char * soap_tmp_xsd__string;
	soap_default_zkreg__regHostResponse(soap, &soap_tmp_zkreg__regHostResponse);
	soap_tmp_xsd__string = NULL;
	soap_tmp_zkreg__regHostResponse.token = &soap_tmp_xsd__string;
	soap_default_zkreg__regHost(soap, &soap_tmp_zkreg__regHost);
	if (!soap_get_zkreg__regHost(soap, &soap_tmp_zkreg__regHost, "zkreg:regHost", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkreg__regHost(soap, soap_tmp_zkreg__regHost.zkreg__regHostReq, soap_tmp_zkreg__regHostResponse.token);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkreg__regHostResponse(soap, &soap_tmp_zkreg__regHostResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__regHostResponse(soap, &soap_tmp_zkreg__regHostResponse, "zkreg:regHostResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__regHostResponse(soap, &soap_tmp_zkreg__regHostResponse, "zkreg:regHostResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkreg__unregHost(struct soap *soap)
{	struct zkreg__unregHost soap_tmp_zkreg__unregHost;
	struct zkreg__unregHostResponse soap_tmp_zkreg__unregHostResponse;
	int soap_tmp_int;
	soap_default_zkreg__unregHostResponse(soap, &soap_tmp_zkreg__unregHostResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_zkreg__unregHostResponse.code = &soap_tmp_int;
	soap_default_zkreg__unregHost(soap, &soap_tmp_zkreg__unregHost);
	if (!soap_get_zkreg__unregHost(soap, &soap_tmp_zkreg__unregHost, "zkreg:unregHost", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkreg__unregHost(soap, soap_tmp_zkreg__unregHost.zkreg__unRegHoststring, soap_tmp_zkreg__unregHostResponse.code);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkreg__unregHostResponse(soap, &soap_tmp_zkreg__unregHostResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__unregHostResponse(soap, &soap_tmp_zkreg__unregHostResponse, "zkreg:unregHostResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__unregHostResponse(soap, &soap_tmp_zkreg__unregHostResponse, "zkreg:unregHostResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkreg__regService(struct soap *soap)
{	struct zkreg__regService soap_tmp_zkreg__regService;
	struct zkreg__regServiceResponse soap_tmp_zkreg__regServiceResponse;
	char * soap_tmp_xsd__string;
	soap_default_zkreg__regServiceResponse(soap, &soap_tmp_zkreg__regServiceResponse);
	soap_tmp_xsd__string = NULL;
	soap_tmp_zkreg__regServiceResponse.token = &soap_tmp_xsd__string;
	soap_default_zkreg__regService(soap, &soap_tmp_zkreg__regService);
	if (!soap_get_zkreg__regService(soap, &soap_tmp_zkreg__regService, "zkreg:regService", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkreg__regService(soap, soap_tmp_zkreg__regService.zkreg__regServiceReq, soap_tmp_zkreg__regServiceResponse.token);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkreg__regServiceResponse(soap, &soap_tmp_zkreg__regServiceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__regServiceResponse(soap, &soap_tmp_zkreg__regServiceResponse, "zkreg:regServiceResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__regServiceResponse(soap, &soap_tmp_zkreg__regServiceResponse, "zkreg:regServiceResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkreg__unregService(struct soap *soap)
{	struct zkreg__unregService soap_tmp_zkreg__unregService;
	struct zkreg__unregServiceResponse soap_tmp_zkreg__unregServiceResponse;
	int soap_tmp_int;
	soap_default_zkreg__unregServiceResponse(soap, &soap_tmp_zkreg__unregServiceResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_zkreg__unregServiceResponse.code = &soap_tmp_int;
	soap_default_zkreg__unregService(soap, &soap_tmp_zkreg__unregService);
	if (!soap_get_zkreg__unregService(soap, &soap_tmp_zkreg__unregService, "zkreg:unregService", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkreg__unregService(soap, soap_tmp_zkreg__unregService.zkreg__unregServicestring, soap_tmp_zkreg__unregServiceResponse.code);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkreg__unregServiceResponse(soap, &soap_tmp_zkreg__unregServiceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__unregServiceResponse(soap, &soap_tmp_zkreg__unregServiceResponse, "zkreg:unregServiceResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__unregServiceResponse(soap, &soap_tmp_zkreg__unregServiceResponse, "zkreg:unregServiceResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkreg__regDevice(struct soap *soap)
{	struct zkreg__regDevice soap_tmp_zkreg__regDevice;
	struct zkreg__regDeviceResponse soap_tmp_zkreg__regDeviceResponse;
	char * soap_tmp_xsd__string;
	soap_default_zkreg__regDeviceResponse(soap, &soap_tmp_zkreg__regDeviceResponse);
	soap_tmp_xsd__string = NULL;
	soap_tmp_zkreg__regDeviceResponse.token = &soap_tmp_xsd__string;
	soap_default_zkreg__regDevice(soap, &soap_tmp_zkreg__regDevice);
	if (!soap_get_zkreg__regDevice(soap, &soap_tmp_zkreg__regDevice, "zkreg:regDevice", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkreg__regDevice(soap, soap_tmp_zkreg__regDevice.zkreg__regDeviceReq, soap_tmp_zkreg__regDeviceResponse.token);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkreg__regDeviceResponse(soap, &soap_tmp_zkreg__regDeviceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__regDeviceResponse(soap, &soap_tmp_zkreg__regDeviceResponse, "zkreg:regDeviceResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__regDeviceResponse(soap, &soap_tmp_zkreg__regDeviceResponse, "zkreg:regDeviceResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkreg__unregDevice(struct soap *soap)
{	struct zkreg__unregDevice soap_tmp_zkreg__unregDevice;
	struct zkreg__unregDeviceResponse soap_tmp_zkreg__unregDeviceResponse;
	int soap_tmp_int;
	soap_default_zkreg__unregDeviceResponse(soap, &soap_tmp_zkreg__unregDeviceResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_zkreg__unregDeviceResponse.code = &soap_tmp_int;
	soap_default_zkreg__unregDevice(soap, &soap_tmp_zkreg__unregDevice);
	if (!soap_get_zkreg__unregDevice(soap, &soap_tmp_zkreg__unregDevice, "zkreg:unregDevice", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkreg__unregDevice(soap, soap_tmp_zkreg__unregDevice.zkreg__unregDevciestring, soap_tmp_zkreg__unregDeviceResponse.code);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkreg__unregDeviceResponse(soap, &soap_tmp_zkreg__unregDeviceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__unregDeviceResponse(soap, &soap_tmp_zkreg__unregDeviceResponse, "zkreg:unregDeviceResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__unregDeviceResponse(soap, &soap_tmp_zkreg__unregDeviceResponse, "zkreg:unregDeviceResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkreg__heartBeat(struct soap *soap)
{	struct zkreg__heartBeat soap_tmp_zkreg__heartBeat;
	struct zkreg__heartBeatResponse soap_tmp_zkreg__heartBeatResponse;
	int soap_tmp_int;
	soap_default_zkreg__heartBeatResponse(soap, &soap_tmp_zkreg__heartBeatResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_zkreg__heartBeatResponse.code = &soap_tmp_int;
	soap_default_zkreg__heartBeat(soap, &soap_tmp_zkreg__heartBeat);
	if (!soap_get_zkreg__heartBeat(soap, &soap_tmp_zkreg__heartBeat, "zkreg:heartBeat", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkreg__heartBeat(soap, soap_tmp_zkreg__heartBeat.zkreg__heartBeatstring, soap_tmp_zkreg__heartBeatResponse.code);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkreg__heartBeatResponse(soap, &soap_tmp_zkreg__heartBeatResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__heartBeatResponse(soap, &soap_tmp_zkreg__heartBeatResponse, "zkreg:heartBeatResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__heartBeatResponse(soap, &soap_tmp_zkreg__heartBeatResponse, "zkreg:heartBeatResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkreg__setShowName(struct soap *soap)
{	struct zkreg__setShowName soap_tmp_zkreg__setShowName;
	struct zkreg__setShowNameResponse soap_tmp_zkreg__setShowNameResponse;
	int soap_tmp_int;
	soap_default_zkreg__setShowNameResponse(soap, &soap_tmp_zkreg__setShowNameResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_zkreg__setShowNameResponse.code = &soap_tmp_int;
	soap_default_zkreg__setShowName(soap, &soap_tmp_zkreg__setShowName);
	if (!soap_get_zkreg__setShowName(soap, &soap_tmp_zkreg__setShowName, "zkreg:setShowName", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkreg__setShowName(soap, soap_tmp_zkreg__setShowName.zkreg__setShowNameReq, soap_tmp_zkreg__setShowName.showname, soap_tmp_zkreg__setShowNameResponse.code);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkreg__setShowNameResponse(soap, &soap_tmp_zkreg__setShowNameResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__setShowNameResponse(soap, &soap_tmp_zkreg__setShowNameResponse, "zkreg:setShowNameResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__setShowNameResponse(soap, &soap_tmp_zkreg__setShowNameResponse, "zkreg:setShowNameResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkq__getAllMses(struct soap *soap)
{	struct zkq__getAllMses soap_tmp_zkq__getAllMses;
	struct zkq__getAllMsesResponse soap_tmp_zkq__getAllMsesResponse;
	struct zkreg__Mses soap_tmp_zkreg__Mses;
	soap_default_zkq__getAllMsesResponse(soap, &soap_tmp_zkq__getAllMsesResponse);
	soap_default_zkreg__Mses(soap, &soap_tmp_zkreg__Mses);
	soap_tmp_zkq__getAllMsesResponse.mses = &soap_tmp_zkreg__Mses;
	soap_default_zkq__getAllMses(soap, &soap_tmp_zkq__getAllMses);
	if (!soap_get_zkq__getAllMses(soap, &soap_tmp_zkq__getAllMses, "zkq:getAllMses", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkq__getAllMses(soap, soap_tmp_zkq__getAllMses.zkq__getAllMsesoffline, soap_tmp_zkq__getAllMsesResponse.mses);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllMsesResponse(soap, &soap_tmp_zkq__getAllMsesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllMsesResponse(soap, &soap_tmp_zkq__getAllMsesResponse, "zkq:getAllMsesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllMsesResponse(soap, &soap_tmp_zkq__getAllMsesResponse, "zkq:getAllMsesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkq__getAllHosts(struct soap *soap)
{	struct zkq__getAllHosts soap_tmp_zkq__getAllHosts;
	struct zkq__getAllHostsResponse soap_tmp_zkq__getAllHostsResponse;
	struct zkreg__Hosts soap_tmp_zkreg__Hosts;
	soap_default_zkq__getAllHostsResponse(soap, &soap_tmp_zkq__getAllHostsResponse);
	soap_default_zkreg__Hosts(soap, &soap_tmp_zkreg__Hosts);
	soap_tmp_zkq__getAllHostsResponse.hosts = &soap_tmp_zkreg__Hosts;
	soap_default_zkq__getAllHosts(soap, &soap_tmp_zkq__getAllHosts);
	if (!soap_get_zkq__getAllHosts(soap, &soap_tmp_zkq__getAllHosts, "zkq:getAllHosts", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkq__getAllHosts(soap, soap_tmp_zkq__getAllHosts.zkq__getAllHostsoffline, soap_tmp_zkq__getAllHostsResponse.hosts);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllHostsResponse(soap, &soap_tmp_zkq__getAllHostsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllHostsResponse(soap, &soap_tmp_zkq__getAllHostsResponse, "zkq:getAllHostsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllHostsResponse(soap, &soap_tmp_zkq__getAllHostsResponse, "zkq:getAllHostsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkq__getAllServices(struct soap *soap)
{	struct zkq__getAllServices soap_tmp_zkq__getAllServices;
	struct zkq__getAllServicesResponse soap_tmp_zkq__getAllServicesResponse;
	struct zkreg__Services soap_tmp_zkreg__Services;
	soap_default_zkq__getAllServicesResponse(soap, &soap_tmp_zkq__getAllServicesResponse);
	soap_default_zkreg__Services(soap, &soap_tmp_zkreg__Services);
	soap_tmp_zkq__getAllServicesResponse.services = &soap_tmp_zkreg__Services;
	soap_default_zkq__getAllServices(soap, &soap_tmp_zkq__getAllServices);
	if (!soap_get_zkq__getAllServices(soap, &soap_tmp_zkq__getAllServices, "zkq:getAllServices", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkq__getAllServices(soap, soap_tmp_zkq__getAllServices.zkq__getAllServiceoffline, soap_tmp_zkq__getAllServicesResponse.services);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllServicesResponse(soap, &soap_tmp_zkq__getAllServicesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllServicesResponse(soap, &soap_tmp_zkq__getAllServicesResponse, "zkq:getAllServicesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllServicesResponse(soap, &soap_tmp_zkq__getAllServicesResponse, "zkq:getAllServicesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkq__getAllDevices(struct soap *soap)
{	struct zkq__getAllDevices soap_tmp_zkq__getAllDevices;
	struct zkq__getAllDevicesResponse soap_tmp_zkq__getAllDevicesResponse;
	struct zkreg__Devices soap_tmp_zkreg__Devices;
	soap_default_zkq__getAllDevicesResponse(soap, &soap_tmp_zkq__getAllDevicesResponse);
	soap_default_zkreg__Devices(soap, &soap_tmp_zkreg__Devices);
	soap_tmp_zkq__getAllDevicesResponse.devices = &soap_tmp_zkreg__Devices;
	soap_default_zkq__getAllDevices(soap, &soap_tmp_zkq__getAllDevices);
	if (!soap_get_zkq__getAllDevices(soap, &soap_tmp_zkq__getAllDevices, "zkq:getAllDevices", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkq__getAllDevices(soap, soap_tmp_zkq__getAllDevices.zkq__getAllDevicesoffline, soap_tmp_zkq__getAllDevicesResponse.devices);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllDevicesResponse(soap, &soap_tmp_zkq__getAllDevicesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllDevicesResponse(soap, &soap_tmp_zkq__getAllDevicesResponse, "zkq:getAllDevicesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllDevicesResponse(soap, &soap_tmp_zkq__getAllDevicesResponse, "zkq:getAllDevicesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkq__getAllLogics(struct soap *soap)
{	struct zkq__getAllLogics soap_tmp_zkq__getAllLogics;
	struct zkq__getAllLogicsResponse soap_tmp_zkq__getAllLogicsResponse;
	struct zkreg__Logics soap_tmp_zkreg__Logics;
	soap_default_zkq__getAllLogicsResponse(soap, &soap_tmp_zkq__getAllLogicsResponse);
	soap_default_zkreg__Logics(soap, &soap_tmp_zkreg__Logics);
	soap_tmp_zkq__getAllLogicsResponse.logics = &soap_tmp_zkreg__Logics;
	soap_default_zkq__getAllLogics(soap, &soap_tmp_zkq__getAllLogics);
	if (!soap_get_zkq__getAllLogics(soap, &soap_tmp_zkq__getAllLogics, "zkq:getAllLogics", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkq__getAllLogics(soap, soap_tmp_zkq__getAllLogics.zkq__getAllLogicsoffline, soap_tmp_zkq__getAllLogicsResponse.logics);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllLogicsResponse(soap, &soap_tmp_zkq__getAllLogicsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllLogicsResponse(soap, &soap_tmp_zkq__getAllLogicsResponse, "zkq:getAllLogicsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllLogicsResponse(soap, &soap_tmp_zkq__getAllLogicsResponse, "zkq:getAllLogicsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_zkq__getServicesByType(struct soap *soap)
{	struct zkq__getServicesByType soap_tmp_zkq__getServicesByType;
	struct zkq__getServicesByTypeResponse soap_tmp_zkq__getServicesByTypeResponse;
	struct zkreg__Services soap_tmp_zkreg__Services;
	soap_default_zkq__getServicesByTypeResponse(soap, &soap_tmp_zkq__getServicesByTypeResponse);
	soap_default_zkreg__Services(soap, &soap_tmp_zkreg__Services);
	soap_tmp_zkq__getServicesByTypeResponse.services = &soap_tmp_zkreg__Services;
	soap_default_zkq__getServicesByType(soap, &soap_tmp_zkq__getServicesByType);
	if (!soap_get_zkq__getServicesByType(soap, &soap_tmp_zkq__getServicesByType, "zkq:getServicesByType", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = zkq__getServicesByType(soap, soap_tmp_zkq__getServicesByType.zkq__getServiceByTypeoffline, soap_tmp_zkq__getServicesByType.type, soap_tmp_zkq__getServicesByTypeResponse.services);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_zkq__getServicesByTypeResponse(soap, &soap_tmp_zkq__getServicesByTypeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getServicesByTypeResponse(soap, &soap_tmp_zkq__getServicesByTypeResponse, "zkq:getServicesByTypeResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getServicesByTypeResponse(soap, &soap_tmp_zkq__getServicesByTypeResponse, "zkq:getServicesByTypeResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
