/* soapClient.c
   Generated by gSOAP 2.8.17r from zonekey_sysmgrt.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.17r 2014-02-08 09:03:03 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkreg__regHost(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct zkreg__Host *zkreg__regHostReq, char **token)
{	struct zkreg__regHost soap_tmp_zkreg__regHost;
	struct zkreg__regHostResponse *soap_tmp_zkreg__regHostResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkreg__regHost.zkreg__regHostReq = zkreg__regHostReq;
	soap_serializeheader(soap);
	soap_serialize_zkreg__regHost(soap, &soap_tmp_zkreg__regHost);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__regHost(soap, &soap_tmp_zkreg__regHost, "zkreg:regHost", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__regHost(soap, &soap_tmp_zkreg__regHost, "zkreg:regHost", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!token)
		return soap_closesock(soap);
	*token = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkreg__regHostResponse = soap_get_zkreg__regHostResponse(soap, NULL, "zkreg:regHostResponse", "");
	if (!soap_tmp_zkreg__regHostResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (token && soap_tmp_zkreg__regHostResponse->token)
		*token = *soap_tmp_zkreg__regHostResponse->token;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkreg__unregHost(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *zkreg__unRegHoststring, int *code)
{	struct zkreg__unregHost soap_tmp_zkreg__unregHost;
	struct zkreg__unregHostResponse *soap_tmp_zkreg__unregHostResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkreg__unregHost.zkreg__unRegHoststring = zkreg__unRegHoststring;
	soap_serializeheader(soap);
	soap_serialize_zkreg__unregHost(soap, &soap_tmp_zkreg__unregHost);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__unregHost(soap, &soap_tmp_zkreg__unregHost, "zkreg:unregHost", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__unregHost(soap, &soap_tmp_zkreg__unregHost, "zkreg:unregHost", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!code)
		return soap_closesock(soap);
	soap_default_int(soap, code);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkreg__unregHostResponse = soap_get_zkreg__unregHostResponse(soap, NULL, "zkreg:unregHostResponse", "");
	if (!soap_tmp_zkreg__unregHostResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (code && soap_tmp_zkreg__unregHostResponse->code)
		*code = *soap_tmp_zkreg__unregHostResponse->code;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkreg__regService(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct zkreg__Service *zkreg__regServiceReq, char **token)
{	struct zkreg__regService soap_tmp_zkreg__regService;
	struct zkreg__regServiceResponse *soap_tmp_zkreg__regServiceResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkreg__regService.zkreg__regServiceReq = zkreg__regServiceReq;
	soap_serializeheader(soap);
	soap_serialize_zkreg__regService(soap, &soap_tmp_zkreg__regService);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__regService(soap, &soap_tmp_zkreg__regService, "zkreg:regService", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__regService(soap, &soap_tmp_zkreg__regService, "zkreg:regService", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!token)
		return soap_closesock(soap);
	*token = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkreg__regServiceResponse = soap_get_zkreg__regServiceResponse(soap, NULL, "zkreg:regServiceResponse", "");
	if (!soap_tmp_zkreg__regServiceResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (token && soap_tmp_zkreg__regServiceResponse->token)
		*token = *soap_tmp_zkreg__regServiceResponse->token;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkreg__unregService(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *zkreg__unregServicestring, int *code)
{	struct zkreg__unregService soap_tmp_zkreg__unregService;
	struct zkreg__unregServiceResponse *soap_tmp_zkreg__unregServiceResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkreg__unregService.zkreg__unregServicestring = zkreg__unregServicestring;
	soap_serializeheader(soap);
	soap_serialize_zkreg__unregService(soap, &soap_tmp_zkreg__unregService);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__unregService(soap, &soap_tmp_zkreg__unregService, "zkreg:unregService", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__unregService(soap, &soap_tmp_zkreg__unregService, "zkreg:unregService", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!code)
		return soap_closesock(soap);
	soap_default_int(soap, code);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkreg__unregServiceResponse = soap_get_zkreg__unregServiceResponse(soap, NULL, "zkreg:unregServiceResponse", "");
	if (!soap_tmp_zkreg__unregServiceResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (code && soap_tmp_zkreg__unregServiceResponse->code)
		*code = *soap_tmp_zkreg__unregServiceResponse->code;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkreg__regDevice(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct zkreg__Device *zkreg__regDeviceReq, char **token)
{	struct zkreg__regDevice soap_tmp_zkreg__regDevice;
	struct zkreg__regDeviceResponse *soap_tmp_zkreg__regDeviceResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkreg__regDevice.zkreg__regDeviceReq = zkreg__regDeviceReq;
	soap_serializeheader(soap);
	soap_serialize_zkreg__regDevice(soap, &soap_tmp_zkreg__regDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__regDevice(soap, &soap_tmp_zkreg__regDevice, "zkreg:regDevice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__regDevice(soap, &soap_tmp_zkreg__regDevice, "zkreg:regDevice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!token)
		return soap_closesock(soap);
	*token = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkreg__regDeviceResponse = soap_get_zkreg__regDeviceResponse(soap, NULL, "zkreg:regDeviceResponse", "");
	if (!soap_tmp_zkreg__regDeviceResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (token && soap_tmp_zkreg__regDeviceResponse->token)
		*token = *soap_tmp_zkreg__regDeviceResponse->token;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkreg__unregDevice(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *zkreg__unregDevciestring, int *code)
{	struct zkreg__unregDevice soap_tmp_zkreg__unregDevice;
	struct zkreg__unregDeviceResponse *soap_tmp_zkreg__unregDeviceResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkreg__unregDevice.zkreg__unregDevciestring = zkreg__unregDevciestring;
	soap_serializeheader(soap);
	soap_serialize_zkreg__unregDevice(soap, &soap_tmp_zkreg__unregDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__unregDevice(soap, &soap_tmp_zkreg__unregDevice, "zkreg:unregDevice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__unregDevice(soap, &soap_tmp_zkreg__unregDevice, "zkreg:unregDevice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!code)
		return soap_closesock(soap);
	soap_default_int(soap, code);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkreg__unregDeviceResponse = soap_get_zkreg__unregDeviceResponse(soap, NULL, "zkreg:unregDeviceResponse", "");
	if (!soap_tmp_zkreg__unregDeviceResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (code && soap_tmp_zkreg__unregDeviceResponse->code)
		*code = *soap_tmp_zkreg__unregDeviceResponse->code;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkreg__heartBeat(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *zkreg__heartBeatstring, int *code)
{	struct zkreg__heartBeat soap_tmp_zkreg__heartBeat;
	struct zkreg__heartBeatResponse *soap_tmp_zkreg__heartBeatResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkreg__heartBeat.zkreg__heartBeatstring = zkreg__heartBeatstring;
	soap_serializeheader(soap);
	soap_serialize_zkreg__heartBeat(soap, &soap_tmp_zkreg__heartBeat);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__heartBeat(soap, &soap_tmp_zkreg__heartBeat, "zkreg:heartBeat", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__heartBeat(soap, &soap_tmp_zkreg__heartBeat, "zkreg:heartBeat", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!code)
		return soap_closesock(soap);
	soap_default_int(soap, code);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkreg__heartBeatResponse = soap_get_zkreg__heartBeatResponse(soap, NULL, "zkreg:heartBeatResponse", "");
	if (!soap_tmp_zkreg__heartBeatResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (code && soap_tmp_zkreg__heartBeatResponse->code)
		*code = *soap_tmp_zkreg__heartBeatResponse->code;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkreg__setShowName(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *zkreg__setShowNameReq, char *showname, int *code)
{	struct zkreg__setShowName soap_tmp_zkreg__setShowName;
	struct zkreg__setShowNameResponse *soap_tmp_zkreg__setShowNameResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkreg__setShowName.zkreg__setShowNameReq = zkreg__setShowNameReq;
	soap_tmp_zkreg__setShowName.showname = showname;
	soap_serializeheader(soap);
	soap_serialize_zkreg__setShowName(soap, &soap_tmp_zkreg__setShowName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkreg__setShowName(soap, &soap_tmp_zkreg__setShowName, "zkreg:setShowName", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkreg__setShowName(soap, &soap_tmp_zkreg__setShowName, "zkreg:setShowName", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!code)
		return soap_closesock(soap);
	soap_default_int(soap, code);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkreg__setShowNameResponse = soap_get_zkreg__setShowNameResponse(soap, NULL, "zkreg:setShowNameResponse", "");
	if (!soap_tmp_zkreg__setShowNameResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (code && soap_tmp_zkreg__setShowNameResponse->code)
		*code = *soap_tmp_zkreg__setShowNameResponse->code;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkq__getAllMses(struct soap *soap, const char *soap_endpoint, const char *soap_action, enum xsd__boolean zkq__getAllMsesoffline, struct zkreg__Mses *mses)
{	struct zkq__getAllMses soap_tmp_zkq__getAllMses;
	struct zkq__getAllMsesResponse *soap_tmp_zkq__getAllMsesResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkq__getAllMses.zkq__getAllMsesoffline = zkq__getAllMsesoffline;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllMses(soap, &soap_tmp_zkq__getAllMses);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllMses(soap, &soap_tmp_zkq__getAllMses, "zkq:getAllMses", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllMses(soap, &soap_tmp_zkq__getAllMses, "zkq:getAllMses", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!mses)
		return soap_closesock(soap);
	soap_default_zkreg__Mses(soap, mses);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkq__getAllMsesResponse = soap_get_zkq__getAllMsesResponse(soap, NULL, "zkq:getAllMsesResponse", "");
	if (!soap_tmp_zkq__getAllMsesResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (mses && soap_tmp_zkq__getAllMsesResponse->mses)
		*mses = *soap_tmp_zkq__getAllMsesResponse->mses;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkq__getAllHosts(struct soap *soap, const char *soap_endpoint, const char *soap_action, enum xsd__boolean zkq__getAllHostsoffline, struct zkreg__Hosts *hosts)
{	struct zkq__getAllHosts soap_tmp_zkq__getAllHosts;
	struct zkq__getAllHostsResponse *soap_tmp_zkq__getAllHostsResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkq__getAllHosts.zkq__getAllHostsoffline = zkq__getAllHostsoffline;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllHosts(soap, &soap_tmp_zkq__getAllHosts);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllHosts(soap, &soap_tmp_zkq__getAllHosts, "zkq:getAllHosts", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllHosts(soap, &soap_tmp_zkq__getAllHosts, "zkq:getAllHosts", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!hosts)
		return soap_closesock(soap);
	soap_default_zkreg__Hosts(soap, hosts);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkq__getAllHostsResponse = soap_get_zkq__getAllHostsResponse(soap, NULL, "zkq:getAllHostsResponse", "");
	if (!soap_tmp_zkq__getAllHostsResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (hosts && soap_tmp_zkq__getAllHostsResponse->hosts)
		*hosts = *soap_tmp_zkq__getAllHostsResponse->hosts;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkq__getAllServices(struct soap *soap, const char *soap_endpoint, const char *soap_action, enum xsd__boolean zkq__getAllServiceoffline, struct zkreg__Services *services)
{	struct zkq__getAllServices soap_tmp_zkq__getAllServices;
	struct zkq__getAllServicesResponse *soap_tmp_zkq__getAllServicesResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkq__getAllServices.zkq__getAllServiceoffline = zkq__getAllServiceoffline;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllServices(soap, &soap_tmp_zkq__getAllServices);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllServices(soap, &soap_tmp_zkq__getAllServices, "zkq:getAllServices", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllServices(soap, &soap_tmp_zkq__getAllServices, "zkq:getAllServices", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!services)
		return soap_closesock(soap);
	soap_default_zkreg__Services(soap, services);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkq__getAllServicesResponse = soap_get_zkq__getAllServicesResponse(soap, NULL, "zkq:getAllServicesResponse", "");
	if (!soap_tmp_zkq__getAllServicesResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (services && soap_tmp_zkq__getAllServicesResponse->services)
		*services = *soap_tmp_zkq__getAllServicesResponse->services;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkq__getAllDevices(struct soap *soap, const char *soap_endpoint, const char *soap_action, enum xsd__boolean zkq__getAllDevicesoffline, struct zkreg__Devices *devices)
{	struct zkq__getAllDevices soap_tmp_zkq__getAllDevices;
	struct zkq__getAllDevicesResponse *soap_tmp_zkq__getAllDevicesResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkq__getAllDevices.zkq__getAllDevicesoffline = zkq__getAllDevicesoffline;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllDevices(soap, &soap_tmp_zkq__getAllDevices);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllDevices(soap, &soap_tmp_zkq__getAllDevices, "zkq:getAllDevices", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllDevices(soap, &soap_tmp_zkq__getAllDevices, "zkq:getAllDevices", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!devices)
		return soap_closesock(soap);
	soap_default_zkreg__Devices(soap, devices);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkq__getAllDevicesResponse = soap_get_zkq__getAllDevicesResponse(soap, NULL, "zkq:getAllDevicesResponse", "");
	if (!soap_tmp_zkq__getAllDevicesResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (devices && soap_tmp_zkq__getAllDevicesResponse->devices)
		*devices = *soap_tmp_zkq__getAllDevicesResponse->devices;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkq__getAllLogics(struct soap *soap, const char *soap_endpoint, const char *soap_action, enum xsd__boolean zkq__getAllLogicsoffline, struct zkreg__Logics *logics)
{	struct zkq__getAllLogics soap_tmp_zkq__getAllLogics;
	struct zkq__getAllLogicsResponse *soap_tmp_zkq__getAllLogicsResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkq__getAllLogics.zkq__getAllLogicsoffline = zkq__getAllLogicsoffline;
	soap_serializeheader(soap);
	soap_serialize_zkq__getAllLogics(soap, &soap_tmp_zkq__getAllLogics);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getAllLogics(soap, &soap_tmp_zkq__getAllLogics, "zkq:getAllLogics", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getAllLogics(soap, &soap_tmp_zkq__getAllLogics, "zkq:getAllLogics", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!logics)
		return soap_closesock(soap);
	soap_default_zkreg__Logics(soap, logics);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkq__getAllLogicsResponse = soap_get_zkq__getAllLogicsResponse(soap, NULL, "zkq:getAllLogicsResponse", "");
	if (!soap_tmp_zkq__getAllLogicsResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (logics && soap_tmp_zkq__getAllLogicsResponse->logics)
		*logics = *soap_tmp_zkq__getAllLogicsResponse->logics;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkq__getServicesByType(struct soap *soap, const char *soap_endpoint, const char *soap_action, enum xsd__boolean zkq__getServiceByTypeoffline, char *type, struct zkreg__Services *services)
{	struct zkq__getServicesByType soap_tmp_zkq__getServicesByType;
	struct zkq__getServicesByTypeResponse *soap_tmp_zkq__getServicesByTypeResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkq__getServicesByType.zkq__getServiceByTypeoffline = zkq__getServiceByTypeoffline;
	soap_tmp_zkq__getServicesByType.type = type;
	soap_serializeheader(soap);
	soap_serialize_zkq__getServicesByType(soap, &soap_tmp_zkq__getServicesByType);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkq__getServicesByType(soap, &soap_tmp_zkq__getServicesByType, "zkq:getServicesByType", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkq__getServicesByType(soap, &soap_tmp_zkq__getServicesByType, "zkq:getServicesByType", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!services)
		return soap_closesock(soap);
	soap_default_zkreg__Services(soap, services);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkq__getServicesByTypeResponse = soap_get_zkq__getServicesByTypeResponse(soap, NULL, "zkq:getServicesByTypeResponse", "");
	if (!soap_tmp_zkq__getServicesByTypeResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (services && soap_tmp_zkq__getServicesByTypeResponse->services)
		*services = *soap_tmp_zkq__getServicesByTypeResponse->services;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkcfg__getAllKeys(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *notuse, struct zkcfg__Keys *zkcfg__KeysRes)
{	struct zkcfg__getAllKeys soap_tmp_zkcfg__getAllKeys;
	struct zkcfg__getAllKeysResponse *soap_tmp_zkcfg__getAllKeysResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkcfg__getAllKeys.notuse = notuse;
	soap_serializeheader(soap);
	soap_serialize_zkcfg__getAllKeys(soap, &soap_tmp_zkcfg__getAllKeys);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkcfg__getAllKeys(soap, &soap_tmp_zkcfg__getAllKeys, "zkcfg:getAllKeys", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkcfg__getAllKeys(soap, &soap_tmp_zkcfg__getAllKeys, "zkcfg:getAllKeys", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!zkcfg__KeysRes)
		return soap_closesock(soap);
	soap_default_zkcfg__Keys(soap, zkcfg__KeysRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_zkcfg__getAllKeysResponse = soap_get_zkcfg__getAllKeysResponse(soap, NULL, "zkcfg:getAllKeysResponse", "zkcfg:Keys");
	if (!soap_tmp_zkcfg__getAllKeysResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (zkcfg__KeysRes && soap_tmp_zkcfg__getAllKeysResponse->zkcfg__KeysRes)
		*zkcfg__KeysRes = *soap_tmp_zkcfg__getAllKeysResponse->zkcfg__KeysRes;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkcfg__getValue(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *zkcfg__getValueKeyRequest, struct zkcfg__Ret *zkcfg__RetRes)
{	struct zkcfg__getValue soap_tmp_zkcfg__getValue;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkcfg__getValue.zkcfg__getValueKeyRequest = zkcfg__getValueKeyRequest;
	soap_serializeheader(soap);
	soap_serialize_zkcfg__getValue(soap, &soap_tmp_zkcfg__getValue);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkcfg__getValue(soap, &soap_tmp_zkcfg__getValue, "zkcfg:getValue", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkcfg__getValue(soap, &soap_tmp_zkcfg__getValue, "zkcfg:getValue", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!zkcfg__RetRes)
		return soap_closesock(soap);
	soap_default_zkcfg__Ret(soap, zkcfg__RetRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_zkcfg__Ret(soap, zkcfg__RetRes, "zkcfg:RetRes", "zkcfg:Ret");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkcfg__setValue(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *zkcfg__setValueKeyRequest, char *value, struct zkcfg__Ret *zkcfg__RetRes)
{	struct zkcfg__setValue soap_tmp_zkcfg__setValue;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkcfg__setValue.zkcfg__setValueKeyRequest = zkcfg__setValueKeyRequest;
	soap_tmp_zkcfg__setValue.value = value;
	soap_serializeheader(soap);
	soap_serialize_zkcfg__setValue(soap, &soap_tmp_zkcfg__setValue);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkcfg__setValue(soap, &soap_tmp_zkcfg__setValue, "zkcfg:setValue", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkcfg__setValue(soap, &soap_tmp_zkcfg__setValue, "zkcfg:setValue", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!zkcfg__RetRes)
		return soap_closesock(soap);
	soap_default_zkcfg__Ret(soap, zkcfg__RetRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_zkcfg__Ret(soap, zkcfg__RetRes, "zkcfg:RetRes", "zkcfg:Ret");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_zkcfg__delKey(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *zkcfg__delKeyRequest, struct zkcfg__Ret *zkcfg__RetRes)
{	struct zkcfg__delKey soap_tmp_zkcfg__delKey;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_zkcfg__delKey.zkcfg__delKeyRequest = zkcfg__delKeyRequest;
	soap_serializeheader(soap);
	soap_serialize_zkcfg__delKey(soap, &soap_tmp_zkcfg__delKey);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_zkcfg__delKey(soap, &soap_tmp_zkcfg__delKey, "zkcfg:delKey", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_zkcfg__delKey(soap, &soap_tmp_zkcfg__delKey, "zkcfg:delKey", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!zkcfg__RetRes)
		return soap_closesock(soap);
	soap_default_zkcfg__Ret(soap, zkcfg__RetRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_zkcfg__Ret(soap, zkcfg__RetRes, "zkcfg:RetRes", "zkcfg:Ret");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
