// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.17020
//
namespace zkquery {
    
    
    /// <remarks/>
    /// <remarks>
///gSOAP 2.8.17r generated service definition
///</remarks>
    [System.Web.Services.WebServiceBinding(Name="zkq", Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class zkq : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAllMsesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMsesByShownameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllHostsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllServicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllDevicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllLogicsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServicesByTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getParentOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBrothersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMseDescOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHostDescOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServiceDescOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDeviceDescOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLogicDescOperationCompleted;
        
        public zkq() {
            this.Url = "http://localhost:80";
        }
        
        public event getAllMsesCompletedEventHandler getAllMsesCompleted;
        
        public event getMsesByShownameCompletedEventHandler getMsesByShownameCompleted;
        
        public event getAllHostsCompletedEventHandler getAllHostsCompleted;
        
        public event getAllServicesCompletedEventHandler getAllServicesCompleted;
        
        public event getAllDevicesCompletedEventHandler getAllDevicesCompleted;
        
        public event getAllLogicsCompletedEventHandler getAllLogicsCompleted;
        
        public event getServicesByTypeCompletedEventHandler getServicesByTypeCompleted;
        
        public event getParentCompletedEventHandler getParentCompleted;
        
        public event getBrothersCompletedEventHandler getBrothersCompleted;
        
        public event getMseDescCompletedEventHandler getMseDescCompleted;
        
        public event getHostDescCompletedEventHandler getHostDescCompleted;
        
        public event getServiceDescCompletedEventHandler getServiceDescCompleted;
        
        public event getDeviceDescCompletedEventHandler getDeviceDescCompleted;
        
        public event getLogicDescCompletedEventHandler getLogicDescCompleted;
        
        /// <remarks>
///Service definition of function zkq__getAllMses
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllMsesResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetAllMsesResponse getAllMses([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetAllMses getAllMses) {
            object[] results = this.Invoke("getAllMses", new object[] {
                        getAllMses});
            return ((MessageGetAllMsesResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetAllMses(MessageGetAllMses getAllMses, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllMses", new object[] {
                        getAllMses}, callback, asyncState);
        }
        
        public MessageGetAllMsesResponse EndgetAllMses(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetAllMsesResponse)(results[0]));
        }
        
        public void getAllMsesAsync(MessageGetAllMses getAllMses) {
            this.getAllMsesAsync(getAllMses, null);
        }
        
        public void getAllMsesAsync(MessageGetAllMses getAllMses, object userState) {
            if ((this.getAllMsesOperationCompleted == null)) {
                this.getAllMsesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllMsesCompleted);
            }
            this.InvokeAsync("getAllMses", new object[] {
                        getAllMses}, this.getAllMsesOperationCompleted, userState);
        }
        
        private void OngetAllMsesCompleted(object arg) {
            if ((this.getAllMsesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllMsesCompleted(this, new getAllMsesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getMsesByShowname
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMsesByShownameResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetMsesByShownameResponse getMsesByShowname([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetMsesByShowname getMsesByShowname) {
            object[] results = this.Invoke("getMsesByShowname", new object[] {
                        getMsesByShowname});
            return ((MessageGetMsesByShownameResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetMsesByShowname(MessageGetMsesByShowname getMsesByShowname, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getMsesByShowname", new object[] {
                        getMsesByShowname}, callback, asyncState);
        }
        
        public MessageGetMsesByShownameResponse EndgetMsesByShowname(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetMsesByShownameResponse)(results[0]));
        }
        
        public void getMsesByShownameAsync(MessageGetMsesByShowname getMsesByShowname) {
            this.getMsesByShownameAsync(getMsesByShowname, null);
        }
        
        public void getMsesByShownameAsync(MessageGetMsesByShowname getMsesByShowname, object userState) {
            if ((this.getMsesByShownameOperationCompleted == null)) {
                this.getMsesByShownameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMsesByShownameCompleted);
            }
            this.InvokeAsync("getMsesByShowname", new object[] {
                        getMsesByShowname}, this.getMsesByShownameOperationCompleted, userState);
        }
        
        private void OngetMsesByShownameCompleted(object arg) {
            if ((this.getMsesByShownameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMsesByShownameCompleted(this, new getMsesByShownameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getAllHosts
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllHostsResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetAllHostsResponse getAllHosts([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetAllHosts getAllHosts) {
            object[] results = this.Invoke("getAllHosts", new object[] {
                        getAllHosts});
            return ((MessageGetAllHostsResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetAllHosts(MessageGetAllHosts getAllHosts, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllHosts", new object[] {
                        getAllHosts}, callback, asyncState);
        }
        
        public MessageGetAllHostsResponse EndgetAllHosts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetAllHostsResponse)(results[0]));
        }
        
        public void getAllHostsAsync(MessageGetAllHosts getAllHosts) {
            this.getAllHostsAsync(getAllHosts, null);
        }
        
        public void getAllHostsAsync(MessageGetAllHosts getAllHosts, object userState) {
            if ((this.getAllHostsOperationCompleted == null)) {
                this.getAllHostsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllHostsCompleted);
            }
            this.InvokeAsync("getAllHosts", new object[] {
                        getAllHosts}, this.getAllHostsOperationCompleted, userState);
        }
        
        private void OngetAllHostsCompleted(object arg) {
            if ((this.getAllHostsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllHostsCompleted(this, new getAllHostsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getAllServices
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllServicesResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetAllServicesResponse getAllServices([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetAllServices getAllServices) {
            object[] results = this.Invoke("getAllServices", new object[] {
                        getAllServices});
            return ((MessageGetAllServicesResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetAllServices(MessageGetAllServices getAllServices, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllServices", new object[] {
                        getAllServices}, callback, asyncState);
        }
        
        public MessageGetAllServicesResponse EndgetAllServices(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetAllServicesResponse)(results[0]));
        }
        
        public void getAllServicesAsync(MessageGetAllServices getAllServices) {
            this.getAllServicesAsync(getAllServices, null);
        }
        
        public void getAllServicesAsync(MessageGetAllServices getAllServices, object userState) {
            if ((this.getAllServicesOperationCompleted == null)) {
                this.getAllServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllServicesCompleted);
            }
            this.InvokeAsync("getAllServices", new object[] {
                        getAllServices}, this.getAllServicesOperationCompleted, userState);
        }
        
        private void OngetAllServicesCompleted(object arg) {
            if ((this.getAllServicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllServicesCompleted(this, new getAllServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getAllDevices
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllDevicesResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetAllDevicesResponse getAllDevices([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetAllDevices getAllDevices) {
            object[] results = this.Invoke("getAllDevices", new object[] {
                        getAllDevices});
            return ((MessageGetAllDevicesResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetAllDevices(MessageGetAllDevices getAllDevices, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllDevices", new object[] {
                        getAllDevices}, callback, asyncState);
        }
        
        public MessageGetAllDevicesResponse EndgetAllDevices(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetAllDevicesResponse)(results[0]));
        }
        
        public void getAllDevicesAsync(MessageGetAllDevices getAllDevices) {
            this.getAllDevicesAsync(getAllDevices, null);
        }
        
        public void getAllDevicesAsync(MessageGetAllDevices getAllDevices, object userState) {
            if ((this.getAllDevicesOperationCompleted == null)) {
                this.getAllDevicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllDevicesCompleted);
            }
            this.InvokeAsync("getAllDevices", new object[] {
                        getAllDevices}, this.getAllDevicesOperationCompleted, userState);
        }
        
        private void OngetAllDevicesCompleted(object arg) {
            if ((this.getAllDevicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllDevicesCompleted(this, new getAllDevicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getAllLogics
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllLogicsResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetAllLogicsResponse getAllLogics([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetAllLogics getAllLogics) {
            object[] results = this.Invoke("getAllLogics", new object[] {
                        getAllLogics});
            return ((MessageGetAllLogicsResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetAllLogics(MessageGetAllLogics getAllLogics, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllLogics", new object[] {
                        getAllLogics}, callback, asyncState);
        }
        
        public MessageGetAllLogicsResponse EndgetAllLogics(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetAllLogicsResponse)(results[0]));
        }
        
        public void getAllLogicsAsync(MessageGetAllLogics getAllLogics) {
            this.getAllLogicsAsync(getAllLogics, null);
        }
        
        public void getAllLogicsAsync(MessageGetAllLogics getAllLogics, object userState) {
            if ((this.getAllLogicsOperationCompleted == null)) {
                this.getAllLogicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllLogicsCompleted);
            }
            this.InvokeAsync("getAllLogics", new object[] {
                        getAllLogics}, this.getAllLogicsOperationCompleted, userState);
        }
        
        private void OngetAllLogicsCompleted(object arg) {
            if ((this.getAllLogicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllLogicsCompleted(this, new getAllLogicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getServicesByType
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getServicesByTypeResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetServicesByTypeResponse getServicesByType([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetServicesByType getServicesByType) {
            object[] results = this.Invoke("getServicesByType", new object[] {
                        getServicesByType});
            return ((MessageGetServicesByTypeResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetServicesByType(MessageGetServicesByType getServicesByType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getServicesByType", new object[] {
                        getServicesByType}, callback, asyncState);
        }
        
        public MessageGetServicesByTypeResponse EndgetServicesByType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetServicesByTypeResponse)(results[0]));
        }
        
        public void getServicesByTypeAsync(MessageGetServicesByType getServicesByType) {
            this.getServicesByTypeAsync(getServicesByType, null);
        }
        
        public void getServicesByTypeAsync(MessageGetServicesByType getServicesByType, object userState) {
            if ((this.getServicesByTypeOperationCompleted == null)) {
                this.getServicesByTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServicesByTypeCompleted);
            }
            this.InvokeAsync("getServicesByType", new object[] {
                        getServicesByType}, this.getServicesByTypeOperationCompleted, userState);
        }
        
        private void OngetServicesByTypeCompleted(object arg) {
            if ((this.getServicesByTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServicesByTypeCompleted(this, new getServicesByTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getParent
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getParentResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetParentResponse getParent([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetParent getParent) {
            object[] results = this.Invoke("getParent", new object[] {
                        getParent});
            return ((MessageGetParentResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetParent(MessageGetParent getParent, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getParent", new object[] {
                        getParent}, callback, asyncState);
        }
        
        public MessageGetParentResponse EndgetParent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetParentResponse)(results[0]));
        }
        
        public void getParentAsync(MessageGetParent getParent) {
            this.getParentAsync(getParent, null);
        }
        
        public void getParentAsync(MessageGetParent getParent, object userState) {
            if ((this.getParentOperationCompleted == null)) {
                this.getParentOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetParentCompleted);
            }
            this.InvokeAsync("getParent", new object[] {
                        getParent}, this.getParentOperationCompleted, userState);
        }
        
        private void OngetParentCompleted(object arg) {
            if ((this.getParentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getParentCompleted(this, new getParentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getBrothers
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getBrothersResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetBrothersResponse getBrothers([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetBrothers getBrothers) {
            object[] results = this.Invoke("getBrothers", new object[] {
                        getBrothers});
            return ((MessageGetBrothersResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetBrothers(MessageGetBrothers getBrothers, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getBrothers", new object[] {
                        getBrothers}, callback, asyncState);
        }
        
        public MessageGetBrothersResponse EndgetBrothers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetBrothersResponse)(results[0]));
        }
        
        public void getBrothersAsync(MessageGetBrothers getBrothers) {
            this.getBrothersAsync(getBrothers, null);
        }
        
        public void getBrothersAsync(MessageGetBrothers getBrothers, object userState) {
            if ((this.getBrothersOperationCompleted == null)) {
                this.getBrothersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBrothersCompleted);
            }
            this.InvokeAsync("getBrothers", new object[] {
                        getBrothers}, this.getBrothersOperationCompleted, userState);
        }
        
        private void OngetBrothersCompleted(object arg) {
            if ((this.getBrothersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBrothersCompleted(this, new getBrothersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getMseDesc
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMseDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetMseDescResponse getMseDesc([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetMseDesc getMseDesc) {
            object[] results = this.Invoke("getMseDesc", new object[] {
                        getMseDesc});
            return ((MessageGetMseDescResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetMseDesc(MessageGetMseDesc getMseDesc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getMseDesc", new object[] {
                        getMseDesc}, callback, asyncState);
        }
        
        public MessageGetMseDescResponse EndgetMseDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetMseDescResponse)(results[0]));
        }
        
        public void getMseDescAsync(MessageGetMseDesc getMseDesc) {
            this.getMseDescAsync(getMseDesc, null);
        }
        
        public void getMseDescAsync(MessageGetMseDesc getMseDesc, object userState) {
            if ((this.getMseDescOperationCompleted == null)) {
                this.getMseDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMseDescCompleted);
            }
            this.InvokeAsync("getMseDesc", new object[] {
                        getMseDesc}, this.getMseDescOperationCompleted, userState);
        }
        
        private void OngetMseDescCompleted(object arg) {
            if ((this.getMseDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMseDescCompleted(this, new getMseDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getHostDesc
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getHostDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetHostDescResponse getHostDesc([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetHostDesc getHostDesc) {
            object[] results = this.Invoke("getHostDesc", new object[] {
                        getHostDesc});
            return ((MessageGetHostDescResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetHostDesc(MessageGetHostDesc getHostDesc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getHostDesc", new object[] {
                        getHostDesc}, callback, asyncState);
        }
        
        public MessageGetHostDescResponse EndgetHostDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetHostDescResponse)(results[0]));
        }
        
        public void getHostDescAsync(MessageGetHostDesc getHostDesc) {
            this.getHostDescAsync(getHostDesc, null);
        }
        
        public void getHostDescAsync(MessageGetHostDesc getHostDesc, object userState) {
            if ((this.getHostDescOperationCompleted == null)) {
                this.getHostDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHostDescCompleted);
            }
            this.InvokeAsync("getHostDesc", new object[] {
                        getHostDesc}, this.getHostDescOperationCompleted, userState);
        }
        
        private void OngetHostDescCompleted(object arg) {
            if ((this.getHostDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHostDescCompleted(this, new getHostDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getServiceDesc
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getServiceDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetServiceDescResponse getServiceDesc([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetServiceDesc getServiceDesc) {
            object[] results = this.Invoke("getServiceDesc", new object[] {
                        getServiceDesc});
            return ((MessageGetServiceDescResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetServiceDesc(MessageGetServiceDesc getServiceDesc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getServiceDesc", new object[] {
                        getServiceDesc}, callback, asyncState);
        }
        
        public MessageGetServiceDescResponse EndgetServiceDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetServiceDescResponse)(results[0]));
        }
        
        public void getServiceDescAsync(MessageGetServiceDesc getServiceDesc) {
            this.getServiceDescAsync(getServiceDesc, null);
        }
        
        public void getServiceDescAsync(MessageGetServiceDesc getServiceDesc, object userState) {
            if ((this.getServiceDescOperationCompleted == null)) {
                this.getServiceDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServiceDescCompleted);
            }
            this.InvokeAsync("getServiceDesc", new object[] {
                        getServiceDesc}, this.getServiceDescOperationCompleted, userState);
        }
        
        private void OngetServiceDescCompleted(object arg) {
            if ((this.getServiceDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServiceDescCompleted(this, new getServiceDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getDeviceDesc
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDeviceDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetDeviceDescResponse getDeviceDesc([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetDeviceDesc getDeviceDesc) {
            object[] results = this.Invoke("getDeviceDesc", new object[] {
                        getDeviceDesc});
            return ((MessageGetDeviceDescResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetDeviceDesc(MessageGetDeviceDesc getDeviceDesc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDeviceDesc", new object[] {
                        getDeviceDesc}, callback, asyncState);
        }
        
        public MessageGetDeviceDescResponse EndgetDeviceDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetDeviceDescResponse)(results[0]));
        }
        
        public void getDeviceDescAsync(MessageGetDeviceDesc getDeviceDesc) {
            this.getDeviceDescAsync(getDeviceDesc, null);
        }
        
        public void getDeviceDescAsync(MessageGetDeviceDesc getDeviceDesc, object userState) {
            if ((this.getDeviceDescOperationCompleted == null)) {
                this.getDeviceDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDeviceDescCompleted);
            }
            this.InvokeAsync("getDeviceDesc", new object[] {
                        getDeviceDesc}, this.getDeviceDescOperationCompleted, userState);
        }
        
        private void OngetDeviceDescCompleted(object arg) {
            if ((this.getDeviceDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDeviceDescCompleted(this, new getDeviceDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Service definition of function zkq__getLogicDesc
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getLogicDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public MessageGetLogicDescResponse getLogicDesc([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")] MessageGetLogicDesc getLogicDesc) {
            object[] results = this.Invoke("getLogicDesc", new object[] {
                        getLogicDesc});
            return ((MessageGetLogicDescResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetLogicDesc(MessageGetLogicDesc getLogicDesc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLogicDesc", new object[] {
                        getLogicDesc}, callback, asyncState);
        }
        
        public MessageGetLogicDescResponse EndgetLogicDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetLogicDescResponse)(results[0]));
        }
        
        public void getLogicDescAsync(MessageGetLogicDesc getLogicDesc) {
            this.getLogicDescAsync(getLogicDesc, null);
        }
        
        public void getLogicDescAsync(MessageGetLogicDesc getLogicDesc, object userState) {
            if ((this.getLogicDescOperationCompleted == null)) {
                this.getLogicDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLogicDescCompleted);
            }
            this.InvokeAsync("getLogicDesc", new object[] {
                        getLogicDesc}, this.getLogicDescOperationCompleted, userState);
        }
        
        private void OngetLogicDescCompleted(object arg) {
            if ((this.getLogicDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLogicDescCompleted(this, new getLogicDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllMses", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllMses {
        
        private bool getAllMsesofflineField;
        
        /// <remarks/>
        public bool getAllMsesoffline {
            get {
                return this.getAllMsesofflineField;
            }
            set {
                this.getAllMsesofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllMsesResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllMsesResponse {
        
        private Mse[] msesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Mse[] mses {
            get {
                return this.msesField;
            }
            set {
                this.msesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Mse {
        
        private string nameField;
        
        private Catalog catalogField;
        
        private string parentField;
        
        private string shownameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField;
            }
            set {
                this.shownameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public enum Catalog {
        
        /// <remarks/>
        Host,
        
        /// <remarks/>
        Service,
        
        /// <remarks/>
        Device,
        
        /// <remarks/>
        Logic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getMsesByShowname", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetMsesByShowname {
        
        private string shownameField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField1;
            }
            set {
                this.shownameField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getMsesByShownameResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetMsesByShownameResponse {
        
        private Mse[] msesField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Mse[] mses {
            get {
                return this.msesField1;
            }
            set {
                this.msesField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllHosts", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllHosts {
        
        private bool getAllHostsofflineField;
        
        /// <remarks/>
        public bool getAllHostsoffline {
            get {
                return this.getAllHostsofflineField;
            }
            set {
                this.getAllHostsofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllHostsResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllHostsResponse {
        
        private Host[] hostsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Host[] hosts {
            get {
                return this.hostsField;
            }
            set {
                this.hostsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Host {
        
        private string nameField1;
        
        private Catalog catalogField1;
        
        private string[] ipsField;
        
        private string parentField1;
        
        private string shownameField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField1;
            }
            set {
                this.nameField1 = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField1;
            }
            set {
                this.catalogField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item")]
        public string[] ips {
            get {
                return this.ipsField;
            }
            set {
                this.ipsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField1;
            }
            set {
                this.parentField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField2;
            }
            set {
                this.shownameField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllServices", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllServices {
        
        private bool getAllServiceofflineField;
        
        /// <remarks/>
        public bool getAllServiceoffline {
            get {
                return this.getAllServiceofflineField;
            }
            set {
                this.getAllServiceofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllServicesResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllServicesResponse {
        
        private Service[] servicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Service[] services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Service {
        
        private string nameField2;
        
        private Catalog catalogField2;
        
        private string hostnameField;
        
        private string typeField;
        
        private string[] urlsField;
        
        private string parentField2;
        
        private string versionField;
        
        private string shownameField3;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField2;
            }
            set {
                this.nameField2 = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField2;
            }
            set {
                this.catalogField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item")]
        public string[] urls {
            get {
                return this.urlsField;
            }
            set {
                this.urlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField2;
            }
            set {
                this.parentField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField3;
            }
            set {
                this.shownameField3 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllDevices", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllDevices {
        
        private bool getAllDevicesofflineField;
        
        /// <remarks/>
        public bool getAllDevicesoffline {
            get {
                return this.getAllDevicesofflineField;
            }
            set {
                this.getAllDevicesofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllDevicesResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllDevicesResponse {
        
        private Device[] devicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Device[] devices {
            get {
                return this.devicesField;
            }
            set {
                this.devicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Device {
        
        private string nameField3;
        
        private Catalog catalogField3;
        
        private string hostnameField1;
        
        private string typeField1;
        
        private string parentField3;
        
        private string vendorField;
        
        private string modelField;
        
        private string serialField;
        
        private string versionField1;
        
        private string shownameField4;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField3;
            }
            set {
                this.nameField3 = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField3;
            }
            set {
                this.catalogField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hostname {
            get {
                return this.hostnameField1;
            }
            set {
                this.hostnameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField1;
            }
            set {
                this.typeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField3;
            }
            set {
                this.parentField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField1;
            }
            set {
                this.versionField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField4;
            }
            set {
                this.shownameField4 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllLogics", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllLogics {
        
        private bool getAllLogicsofflineField;
        
        /// <remarks/>
        public bool getAllLogicsoffline {
            get {
                return this.getAllLogicsofflineField;
            }
            set {
                this.getAllLogicsofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getAllLogicsResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetAllLogicsResponse {
        
        private Logic[] logicsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Logic[] logics {
            get {
                return this.logicsField;
            }
            set {
                this.logicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Logic {
        
        private string nameField4;
        
        private Catalog catalogField4;
        
        private string parentField4;
        
        private string childrenField;
        
        private int childnumField;
        
        private bool childnumSpecifiedField;
        
        private string shownameField5;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField4;
            }
            set {
                this.nameField4 = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField4;
            }
            set {
                this.catalogField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField4;
            }
            set {
                this.parentField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        public int childnum {
            get {
                return this.childnumField;
            }
            set {
                this.childnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool childnumSpecified {
            get {
                return this.childnumSpecifiedField;
            }
            set {
                this.childnumSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField5;
            }
            set {
                this.shownameField5 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getServicesByType", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetServicesByType {
        
        private bool getServiceByTypeofflineField;
        
        private string typeField2;
        
        /// <remarks/>
        public bool getServiceByTypeoffline {
            get {
                return this.getServiceByTypeofflineField;
            }
            set {
                this.getServiceByTypeofflineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField2;
            }
            set {
                this.typeField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getServicesByTypeResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetServicesByTypeResponse {
        
        private Service[] servicesField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Service[] services {
            get {
                return this.servicesField1;
            }
            set {
                this.servicesField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getParent", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetParent {
        
        private string getParentNameField;
        
        /// <remarks/>
        public string getParentName {
            get {
                return this.getParentNameField;
            }
            set {
                this.getParentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getParentResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetParentResponse {
        
        private Logic[] lsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Logic[] ls {
            get {
                return this.lsField;
            }
            set {
                this.lsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getBrothers", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetBrothers {
        
        private string getBrothersNameField;
        
        /// <remarks/>
        public string getBrothersName {
            get {
                return this.getBrothersNameField;
            }
            set {
                this.getBrothersNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getBrothersResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetBrothersResponse {
        
        private Brother[] brothersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="item", IsNullable=false)]
        public Brother[] brothers {
            get {
                return this.brothersField;
            }
            set {
                this.brothersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class Brother {
        
        private string parentField5;
        
        private string brothersField1;
        
        private int brothernumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField5;
            }
            set {
                this.parentField5 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string brothers {
            get {
                return this.brothersField1;
            }
            set {
                this.brothersField1 = value;
            }
        }
        
        /// <remarks/>
        public int brothernum {
            get {
                return this.brothernumField;
            }
            set {
                this.brothernumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getMseDesc", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetMseDesc {
        
        private string getMseNameField;
        
        /// <remarks/>
        public string getMseName {
            get {
                return this.getMseNameField;
            }
            set {
                this.getMseNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getMseDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetMseDescResponse {
        
        private Mse mseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Mse mse {
            get {
                return this.mseField;
            }
            set {
                this.mseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getHostDesc", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetHostDesc {
        
        private string getHostNameField;
        
        /// <remarks/>
        public string getHostName {
            get {
                return this.getHostNameField;
            }
            set {
                this.getHostNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getHostDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetHostDescResponse {
        
        private Host hostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Host host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getServiceDesc", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetServiceDesc {
        
        private string getServiceNameField;
        
        /// <remarks/>
        public string getServiceName {
            get {
                return this.getServiceNameField;
            }
            set {
                this.getServiceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getServiceDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetServiceDescResponse {
        
        private Service serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Service service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getDeviceDesc", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetDeviceDesc {
        
        private string getDeviceNameField;
        
        /// <remarks/>
        public string getDeviceName {
            get {
                return this.getDeviceNameField;
            }
            set {
                this.getDeviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getDeviceDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetDeviceDescResponse {
        
        private Device deviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Device device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getLogicDesc", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetLogicDesc {
        
        private string getLogicNameField;
        
        /// <remarks/>
        public string getLogicName {
            get {
                return this.getLogicNameField;
            }
            set {
                this.getLogicNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    [System.Xml.Serialization.XmlRootAttribute("getLogicDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class MessageGetLogicDescResponse {
        
        private Logic logicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Logic logic {
            get {
                return this.logicField;
            }
            set {
                this.logicField = value;
            }
        }
    }
    
    public partial class getAllMsesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllMsesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetAllMsesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetAllMsesResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getAllMsesCompletedEventHandler(object sender, getAllMsesCompletedEventArgs args);
    
    public partial class getMsesByShownameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMsesByShownameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetMsesByShownameResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetMsesByShownameResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getMsesByShownameCompletedEventHandler(object sender, getMsesByShownameCompletedEventArgs args);
    
    public partial class getAllHostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllHostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetAllHostsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetAllHostsResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getAllHostsCompletedEventHandler(object sender, getAllHostsCompletedEventArgs args);
    
    public partial class getAllServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetAllServicesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetAllServicesResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getAllServicesCompletedEventHandler(object sender, getAllServicesCompletedEventArgs args);
    
    public partial class getAllDevicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllDevicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetAllDevicesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetAllDevicesResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getAllDevicesCompletedEventHandler(object sender, getAllDevicesCompletedEventArgs args);
    
    public partial class getAllLogicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllLogicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetAllLogicsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetAllLogicsResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getAllLogicsCompletedEventHandler(object sender, getAllLogicsCompletedEventArgs args);
    
    public partial class getServicesByTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServicesByTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetServicesByTypeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetServicesByTypeResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getServicesByTypeCompletedEventHandler(object sender, getServicesByTypeCompletedEventArgs args);
    
    public partial class getParentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getParentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetParentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetParentResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getParentCompletedEventHandler(object sender, getParentCompletedEventArgs args);
    
    public partial class getBrothersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBrothersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetBrothersResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetBrothersResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getBrothersCompletedEventHandler(object sender, getBrothersCompletedEventArgs args);
    
    public partial class getMseDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMseDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetMseDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetMseDescResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getMseDescCompletedEventHandler(object sender, getMseDescCompletedEventArgs args);
    
    public partial class getHostDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHostDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetHostDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetHostDescResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getHostDescCompletedEventHandler(object sender, getHostDescCompletedEventArgs args);
    
    public partial class getServiceDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServiceDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetServiceDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetServiceDescResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getServiceDescCompletedEventHandler(object sender, getServiceDescCompletedEventArgs args);
    
    public partial class getDeviceDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDeviceDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetDeviceDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetDeviceDescResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getDeviceDescCompletedEventHandler(object sender, getDeviceDescCompletedEventArgs args);
    
    public partial class getLogicDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLogicDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetLogicDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetLogicDescResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getLogicDescCompletedEventHandler(object sender, getLogicDescCompletedEventArgs args);
}
