//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 
namespace zkquery {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="zkq", Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class zkq : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAllMsesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMsesByShownameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllHostsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllServicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllDevicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllLogicsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServicesByTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getParentOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBrothersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMseDescOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHostDescOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServiceDescOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDeviceDescOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLogicDescOperationCompleted;
        
        /// <remarks/>
        public zkq() {
            this.Url = "http://localhost:80";
        }
        
        /// <remarks/>
        public event getAllMsesCompletedEventHandler getAllMsesCompleted;
        
        /// <remarks/>
        public event getMsesByShownameCompletedEventHandler getMsesByShownameCompleted;
        
        /// <remarks/>
        public event getAllHostsCompletedEventHandler getAllHostsCompleted;
        
        /// <remarks/>
        public event getAllServicesCompletedEventHandler getAllServicesCompleted;
        
        /// <remarks/>
        public event getAllDevicesCompletedEventHandler getAllDevicesCompleted;
        
        /// <remarks/>
        public event getAllLogicsCompletedEventHandler getAllLogicsCompleted;
        
        /// <remarks/>
        public event getServicesByTypeCompletedEventHandler getServicesByTypeCompleted;
        
        /// <remarks/>
        public event getParentCompletedEventHandler getParentCompleted;
        
        /// <remarks/>
        public event getBrothersCompletedEventHandler getBrothersCompleted;
        
        /// <remarks/>
        public event getMseDescCompletedEventHandler getMseDescCompleted;
        
        /// <remarks/>
        public event getHostDescCompletedEventHandler getHostDescCompleted;
        
        /// <remarks/>
        public event getServiceDescCompletedEventHandler getServiceDescCompleted;
        
        /// <remarks/>
        public event getDeviceDescCompletedEventHandler getDeviceDescCompleted;
        
        /// <remarks/>
        public event getLogicDescCompletedEventHandler getLogicDescCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllMsesResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getAllMsesResponse getAllMses([System.Xml.Serialization.XmlElementAttribute("getAllMses", Namespace="http://www.zonekey.com/sysmgrt/query")] getAllMses getAllMses1) {
            object[] results = this.Invoke("getAllMses", new object[] {
                        getAllMses1});
            return ((getAllMsesResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllMses(getAllMses getAllMses1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllMses", new object[] {
                        getAllMses1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getAllMsesResponse EndgetAllMses(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getAllMsesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllMsesAsync(getAllMses getAllMses1) {
            this.getAllMsesAsync(getAllMses1, null);
        }
        
        /// <remarks/>
        public void getAllMsesAsync(getAllMses getAllMses1, object userState) {
            if ((this.getAllMsesOperationCompleted == null)) {
                this.getAllMsesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllMsesOperationCompleted);
            }
            this.InvokeAsync("getAllMses", new object[] {
                        getAllMses1}, this.getAllMsesOperationCompleted, userState);
        }
        
        private void OngetAllMsesOperationCompleted(object arg) {
            if ((this.getAllMsesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllMsesCompleted(this, new getAllMsesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMsesByShownameResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getMsesByShownameResponse getMsesByShowname([System.Xml.Serialization.XmlElementAttribute("getMsesByShowname", Namespace="http://www.zonekey.com/sysmgrt/query")] getMsesByShowname getMsesByShowname1) {
            object[] results = this.Invoke("getMsesByShowname", new object[] {
                        getMsesByShowname1});
            return ((getMsesByShownameResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetMsesByShowname(getMsesByShowname getMsesByShowname1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getMsesByShowname", new object[] {
                        getMsesByShowname1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getMsesByShownameResponse EndgetMsesByShowname(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getMsesByShownameResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getMsesByShownameAsync(getMsesByShowname getMsesByShowname1) {
            this.getMsesByShownameAsync(getMsesByShowname1, null);
        }
        
        /// <remarks/>
        public void getMsesByShownameAsync(getMsesByShowname getMsesByShowname1, object userState) {
            if ((this.getMsesByShownameOperationCompleted == null)) {
                this.getMsesByShownameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMsesByShownameOperationCompleted);
            }
            this.InvokeAsync("getMsesByShowname", new object[] {
                        getMsesByShowname1}, this.getMsesByShownameOperationCompleted, userState);
        }
        
        private void OngetMsesByShownameOperationCompleted(object arg) {
            if ((this.getMsesByShownameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMsesByShownameCompleted(this, new getMsesByShownameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllHostsResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getAllHostsResponse getAllHosts([System.Xml.Serialization.XmlElementAttribute("getAllHosts", Namespace="http://www.zonekey.com/sysmgrt/query")] getAllHosts getAllHosts1) {
            object[] results = this.Invoke("getAllHosts", new object[] {
                        getAllHosts1});
            return ((getAllHostsResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllHosts(getAllHosts getAllHosts1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllHosts", new object[] {
                        getAllHosts1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getAllHostsResponse EndgetAllHosts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getAllHostsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllHostsAsync(getAllHosts getAllHosts1) {
            this.getAllHostsAsync(getAllHosts1, null);
        }
        
        /// <remarks/>
        public void getAllHostsAsync(getAllHosts getAllHosts1, object userState) {
            if ((this.getAllHostsOperationCompleted == null)) {
                this.getAllHostsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllHostsOperationCompleted);
            }
            this.InvokeAsync("getAllHosts", new object[] {
                        getAllHosts1}, this.getAllHostsOperationCompleted, userState);
        }
        
        private void OngetAllHostsOperationCompleted(object arg) {
            if ((this.getAllHostsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllHostsCompleted(this, new getAllHostsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllServicesResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getAllServicesResponse getAllServices([System.Xml.Serialization.XmlElementAttribute("getAllServices", Namespace="http://www.zonekey.com/sysmgrt/query")] getAllServices getAllServices1) {
            object[] results = this.Invoke("getAllServices", new object[] {
                        getAllServices1});
            return ((getAllServicesResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllServices(getAllServices getAllServices1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllServices", new object[] {
                        getAllServices1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getAllServicesResponse EndgetAllServices(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getAllServicesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllServicesAsync(getAllServices getAllServices1) {
            this.getAllServicesAsync(getAllServices1, null);
        }
        
        /// <remarks/>
        public void getAllServicesAsync(getAllServices getAllServices1, object userState) {
            if ((this.getAllServicesOperationCompleted == null)) {
                this.getAllServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllServicesOperationCompleted);
            }
            this.InvokeAsync("getAllServices", new object[] {
                        getAllServices1}, this.getAllServicesOperationCompleted, userState);
        }
        
        private void OngetAllServicesOperationCompleted(object arg) {
            if ((this.getAllServicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllServicesCompleted(this, new getAllServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllDevicesResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getAllDevicesResponse getAllDevices([System.Xml.Serialization.XmlElementAttribute("getAllDevices", Namespace="http://www.zonekey.com/sysmgrt/query")] getAllDevices getAllDevices1) {
            object[] results = this.Invoke("getAllDevices", new object[] {
                        getAllDevices1});
            return ((getAllDevicesResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllDevices(getAllDevices getAllDevices1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllDevices", new object[] {
                        getAllDevices1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getAllDevicesResponse EndgetAllDevices(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getAllDevicesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllDevicesAsync(getAllDevices getAllDevices1) {
            this.getAllDevicesAsync(getAllDevices1, null);
        }
        
        /// <remarks/>
        public void getAllDevicesAsync(getAllDevices getAllDevices1, object userState) {
            if ((this.getAllDevicesOperationCompleted == null)) {
                this.getAllDevicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllDevicesOperationCompleted);
            }
            this.InvokeAsync("getAllDevices", new object[] {
                        getAllDevices1}, this.getAllDevicesOperationCompleted, userState);
        }
        
        private void OngetAllDevicesOperationCompleted(object arg) {
            if ((this.getAllDevicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllDevicesCompleted(this, new getAllDevicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAllLogicsResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getAllLogicsResponse getAllLogics([System.Xml.Serialization.XmlElementAttribute("getAllLogics", Namespace="http://www.zonekey.com/sysmgrt/query")] getAllLogics getAllLogics1) {
            object[] results = this.Invoke("getAllLogics", new object[] {
                        getAllLogics1});
            return ((getAllLogicsResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllLogics(getAllLogics getAllLogics1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllLogics", new object[] {
                        getAllLogics1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getAllLogicsResponse EndgetAllLogics(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getAllLogicsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllLogicsAsync(getAllLogics getAllLogics1) {
            this.getAllLogicsAsync(getAllLogics1, null);
        }
        
        /// <remarks/>
        public void getAllLogicsAsync(getAllLogics getAllLogics1, object userState) {
            if ((this.getAllLogicsOperationCompleted == null)) {
                this.getAllLogicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllLogicsOperationCompleted);
            }
            this.InvokeAsync("getAllLogics", new object[] {
                        getAllLogics1}, this.getAllLogicsOperationCompleted, userState);
        }
        
        private void OngetAllLogicsOperationCompleted(object arg) {
            if ((this.getAllLogicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllLogicsCompleted(this, new getAllLogicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getServicesByTypeResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getServicesByTypeResponse getServicesByType([System.Xml.Serialization.XmlElementAttribute("getServicesByType", Namespace="http://www.zonekey.com/sysmgrt/query")] getServicesByType getServicesByType1) {
            object[] results = this.Invoke("getServicesByType", new object[] {
                        getServicesByType1});
            return ((getServicesByTypeResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetServicesByType(getServicesByType getServicesByType1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getServicesByType", new object[] {
                        getServicesByType1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getServicesByTypeResponse EndgetServicesByType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getServicesByTypeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getServicesByTypeAsync(getServicesByType getServicesByType1) {
            this.getServicesByTypeAsync(getServicesByType1, null);
        }
        
        /// <remarks/>
        public void getServicesByTypeAsync(getServicesByType getServicesByType1, object userState) {
            if ((this.getServicesByTypeOperationCompleted == null)) {
                this.getServicesByTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServicesByTypeOperationCompleted);
            }
            this.InvokeAsync("getServicesByType", new object[] {
                        getServicesByType1}, this.getServicesByTypeOperationCompleted, userState);
        }
        
        private void OngetServicesByTypeOperationCompleted(object arg) {
            if ((this.getServicesByTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServicesByTypeCompleted(this, new getServicesByTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getParentResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getParentResponse getParent([System.Xml.Serialization.XmlElementAttribute("getParent", Namespace="http://www.zonekey.com/sysmgrt/query")] getParent getParent1) {
            object[] results = this.Invoke("getParent", new object[] {
                        getParent1});
            return ((getParentResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetParent(getParent getParent1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getParent", new object[] {
                        getParent1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getParentResponse EndgetParent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getParentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getParentAsync(getParent getParent1) {
            this.getParentAsync(getParent1, null);
        }
        
        /// <remarks/>
        public void getParentAsync(getParent getParent1, object userState) {
            if ((this.getParentOperationCompleted == null)) {
                this.getParentOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetParentOperationCompleted);
            }
            this.InvokeAsync("getParent", new object[] {
                        getParent1}, this.getParentOperationCompleted, userState);
        }
        
        private void OngetParentOperationCompleted(object arg) {
            if ((this.getParentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getParentCompleted(this, new getParentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getBrothersResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getBrothersResponse getBrothers([System.Xml.Serialization.XmlElementAttribute("getBrothers", Namespace="http://www.zonekey.com/sysmgrt/query")] getBrothers getBrothers1) {
            object[] results = this.Invoke("getBrothers", new object[] {
                        getBrothers1});
            return ((getBrothersResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetBrothers(getBrothers getBrothers1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getBrothers", new object[] {
                        getBrothers1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getBrothersResponse EndgetBrothers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getBrothersResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getBrothersAsync(getBrothers getBrothers1) {
            this.getBrothersAsync(getBrothers1, null);
        }
        
        /// <remarks/>
        public void getBrothersAsync(getBrothers getBrothers1, object userState) {
            if ((this.getBrothersOperationCompleted == null)) {
                this.getBrothersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBrothersOperationCompleted);
            }
            this.InvokeAsync("getBrothers", new object[] {
                        getBrothers1}, this.getBrothersOperationCompleted, userState);
        }
        
        private void OngetBrothersOperationCompleted(object arg) {
            if ((this.getBrothersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBrothersCompleted(this, new getBrothersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMseDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getMseDescResponse getMseDesc([System.Xml.Serialization.XmlElementAttribute("getMseDesc", Namespace="http://www.zonekey.com/sysmgrt/query")] getMseDesc getMseDesc1) {
            object[] results = this.Invoke("getMseDesc", new object[] {
                        getMseDesc1});
            return ((getMseDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetMseDesc(getMseDesc getMseDesc1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getMseDesc", new object[] {
                        getMseDesc1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getMseDescResponse EndgetMseDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getMseDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getMseDescAsync(getMseDesc getMseDesc1) {
            this.getMseDescAsync(getMseDesc1, null);
        }
        
        /// <remarks/>
        public void getMseDescAsync(getMseDesc getMseDesc1, object userState) {
            if ((this.getMseDescOperationCompleted == null)) {
                this.getMseDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMseDescOperationCompleted);
            }
            this.InvokeAsync("getMseDesc", new object[] {
                        getMseDesc1}, this.getMseDescOperationCompleted, userState);
        }
        
        private void OngetMseDescOperationCompleted(object arg) {
            if ((this.getMseDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMseDescCompleted(this, new getMseDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getHostDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getHostDescResponse getHostDesc([System.Xml.Serialization.XmlElementAttribute("getHostDesc", Namespace="http://www.zonekey.com/sysmgrt/query")] getHostDesc getHostDesc1) {
            object[] results = this.Invoke("getHostDesc", new object[] {
                        getHostDesc1});
            return ((getHostDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetHostDesc(getHostDesc getHostDesc1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getHostDesc", new object[] {
                        getHostDesc1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getHostDescResponse EndgetHostDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getHostDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getHostDescAsync(getHostDesc getHostDesc1) {
            this.getHostDescAsync(getHostDesc1, null);
        }
        
        /// <remarks/>
        public void getHostDescAsync(getHostDesc getHostDesc1, object userState) {
            if ((this.getHostDescOperationCompleted == null)) {
                this.getHostDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHostDescOperationCompleted);
            }
            this.InvokeAsync("getHostDesc", new object[] {
                        getHostDesc1}, this.getHostDescOperationCompleted, userState);
        }
        
        private void OngetHostDescOperationCompleted(object arg) {
            if ((this.getHostDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHostDescCompleted(this, new getHostDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getServiceDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getServiceDescResponse getServiceDesc([System.Xml.Serialization.XmlElementAttribute("getServiceDesc", Namespace="http://www.zonekey.com/sysmgrt/query")] getServiceDesc getServiceDesc1) {
            object[] results = this.Invoke("getServiceDesc", new object[] {
                        getServiceDesc1});
            return ((getServiceDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetServiceDesc(getServiceDesc getServiceDesc1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getServiceDesc", new object[] {
                        getServiceDesc1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getServiceDescResponse EndgetServiceDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getServiceDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getServiceDescAsync(getServiceDesc getServiceDesc1) {
            this.getServiceDescAsync(getServiceDesc1, null);
        }
        
        /// <remarks/>
        public void getServiceDescAsync(getServiceDesc getServiceDesc1, object userState) {
            if ((this.getServiceDescOperationCompleted == null)) {
                this.getServiceDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServiceDescOperationCompleted);
            }
            this.InvokeAsync("getServiceDesc", new object[] {
                        getServiceDesc1}, this.getServiceDescOperationCompleted, userState);
        }
        
        private void OngetServiceDescOperationCompleted(object arg) {
            if ((this.getServiceDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServiceDescCompleted(this, new getServiceDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDeviceDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getDeviceDescResponse getDeviceDesc([System.Xml.Serialization.XmlElementAttribute("getDeviceDesc", Namespace="http://www.zonekey.com/sysmgrt/query")] getDeviceDesc getDeviceDesc1) {
            object[] results = this.Invoke("getDeviceDesc", new object[] {
                        getDeviceDesc1});
            return ((getDeviceDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDeviceDesc(getDeviceDesc getDeviceDesc1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDeviceDesc", new object[] {
                        getDeviceDesc1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getDeviceDescResponse EndgetDeviceDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getDeviceDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getDeviceDescAsync(getDeviceDesc getDeviceDesc1) {
            this.getDeviceDescAsync(getDeviceDesc1, null);
        }
        
        /// <remarks/>
        public void getDeviceDescAsync(getDeviceDesc getDeviceDesc1, object userState) {
            if ((this.getDeviceDescOperationCompleted == null)) {
                this.getDeviceDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDeviceDescOperationCompleted);
            }
            this.InvokeAsync("getDeviceDesc", new object[] {
                        getDeviceDesc1}, this.getDeviceDescOperationCompleted, userState);
        }
        
        private void OngetDeviceDescOperationCompleted(object arg) {
            if ((this.getDeviceDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDeviceDescCompleted(this, new getDeviceDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getLogicDescResponse", Namespace="http://www.zonekey.com/sysmgrt/query")]
        public getLogicDescResponse getLogicDesc([System.Xml.Serialization.XmlElementAttribute("getLogicDesc", Namespace="http://www.zonekey.com/sysmgrt/query")] getLogicDesc getLogicDesc1) {
            object[] results = this.Invoke("getLogicDesc", new object[] {
                        getLogicDesc1});
            return ((getLogicDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLogicDesc(getLogicDesc getLogicDesc1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLogicDesc", new object[] {
                        getLogicDesc1}, callback, asyncState);
        }
        
        /// <remarks/>
        public getLogicDescResponse EndgetLogicDesc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((getLogicDescResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getLogicDescAsync(getLogicDesc getLogicDesc1) {
            this.getLogicDescAsync(getLogicDesc1, null);
        }
        
        /// <remarks/>
        public void getLogicDescAsync(getLogicDesc getLogicDesc1, object userState) {
            if ((this.getLogicDescOperationCompleted == null)) {
                this.getLogicDescOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLogicDescOperationCompleted);
            }
            this.InvokeAsync("getLogicDesc", new object[] {
                        getLogicDesc1}, this.getLogicDescOperationCompleted, userState);
        }
        
        private void OngetLogicDescOperationCompleted(object arg) {
            if ((this.getLogicDescCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLogicDescCompleted(this, new getLogicDescCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllMses {
        
        private bool getAllMsesofflineField;
        
        /// <remarks/>
        public bool getAllMsesoffline {
            get {
                return this.getAllMsesofflineField;
            }
            set {
                this.getAllMsesofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class Brother {
        
        private string parentField;
        
        private string brothersField;
        
        private int brothernumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string brothers {
            get {
                return this.brothersField;
            }
            set {
                this.brothersField = value;
            }
        }
        
        /// <remarks/>
        public int brothernum {
            get {
                return this.brothernumField;
            }
            set {
                this.brothernumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Logic {
        
        private string nameField;
        
        private Catalog catalogField;
        
        private string parentField;
        
        private string childrenField;
        
        private int childnumField;
        
        private bool childnumFieldSpecified;
        
        private string shownameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        public int childnum {
            get {
                return this.childnumField;
            }
            set {
                this.childnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool childnumSpecified {
            get {
                return this.childnumFieldSpecified;
            }
            set {
                this.childnumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField;
            }
            set {
                this.shownameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public enum Catalog {
        
        /// <remarks/>
        Host,
        
        /// <remarks/>
        Service,
        
        /// <remarks/>
        Device,
        
        /// <remarks/>
        Logic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Device {
        
        private string nameField;
        
        private Catalog catalogField;
        
        private string hostnameField;
        
        private string typeField;
        
        private string parentField;
        
        private string vendorField;
        
        private string modelField;
        
        private string serialField;
        
        private string versionField;
        
        private string shownameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField;
            }
            set {
                this.shownameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Service {
        
        private string nameField;
        
        private Catalog catalogField;
        
        private string hostnameField;
        
        private string typeField;
        
        private string[] urlsField;
        
        private string parentField;
        
        private string versionField;
        
        private string shownameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", DataType="anyURI")]
        public string[] urls {
            get {
                return this.urlsField;
            }
            set {
                this.urlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField;
            }
            set {
                this.shownameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Host {
        
        private string nameField;
        
        private Catalog catalogField;
        
        private string[] ipsField;
        
        private string parentField;
        
        private string shownameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public string[] ips {
            get {
                return this.ipsField;
            }
            set {
                this.ipsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField;
            }
            set {
                this.shownameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zonekey.com/sysmgrt/register")]
    public partial class Mse {
        
        private string nameField;
        
        private Catalog catalogField;
        
        private string parentField;
        
        private string shownameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Catalog catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField;
            }
            set {
                this.shownameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllMsesResponse {
        
        private Mse[] msesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Mse[] mses {
            get {
                return this.msesField;
            }
            set {
                this.msesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getMsesByShowname {
        
        private string shownameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string showname {
            get {
                return this.shownameField;
            }
            set {
                this.shownameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getMsesByShownameResponse {
        
        private Mse[] msesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Mse[] mses {
            get {
                return this.msesField;
            }
            set {
                this.msesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllHosts {
        
        private bool getAllHostsofflineField;
        
        /// <remarks/>
        public bool getAllHostsoffline {
            get {
                return this.getAllHostsofflineField;
            }
            set {
                this.getAllHostsofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllHostsResponse {
        
        private Host[] hostsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Host[] hosts {
            get {
                return this.hostsField;
            }
            set {
                this.hostsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllServices {
        
        private bool getAllServiceofflineField;
        
        /// <remarks/>
        public bool getAllServiceoffline {
            get {
                return this.getAllServiceofflineField;
            }
            set {
                this.getAllServiceofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllServicesResponse {
        
        private Service[] servicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Service[] services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllDevices {
        
        private bool getAllDevicesofflineField;
        
        /// <remarks/>
        public bool getAllDevicesoffline {
            get {
                return this.getAllDevicesofflineField;
            }
            set {
                this.getAllDevicesofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllDevicesResponse {
        
        private Device[] devicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Device[] devices {
            get {
                return this.devicesField;
            }
            set {
                this.devicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllLogics {
        
        private bool getAllLogicsofflineField;
        
        /// <remarks/>
        public bool getAllLogicsoffline {
            get {
                return this.getAllLogicsofflineField;
            }
            set {
                this.getAllLogicsofflineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getAllLogicsResponse {
        
        private Logic[] logicsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Logic[] logics {
            get {
                return this.logicsField;
            }
            set {
                this.logicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getServicesByType {
        
        private bool getServiceByTypeofflineField;
        
        private string typeField;
        
        /// <remarks/>
        public bool getServiceByTypeoffline {
            get {
                return this.getServiceByTypeofflineField;
            }
            set {
                this.getServiceByTypeofflineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getServicesByTypeResponse {
        
        private Service[] servicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Service[] services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getParent {
        
        private string getParentNameField;
        
        /// <remarks/>
        public string getParentName {
            get {
                return this.getParentNameField;
            }
            set {
                this.getParentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getParentResponse {
        
        private Logic[] lsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://www.zonekey.com/sysmgrt/register", IsNullable=false)]
        public Logic[] ls {
            get {
                return this.lsField;
            }
            set {
                this.lsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getBrothers {
        
        private string getBrothersNameField;
        
        /// <remarks/>
        public string getBrothersName {
            get {
                return this.getBrothersNameField;
            }
            set {
                this.getBrothersNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getBrothersResponse {
        
        private Brother[] brothersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public Brother[] brothers {
            get {
                return this.brothersField;
            }
            set {
                this.brothersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getMseDesc {
        
        private string getMseNameField;
        
        /// <remarks/>
        public string getMseName {
            get {
                return this.getMseNameField;
            }
            set {
                this.getMseNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getMseDescResponse {
        
        private Mse mseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Mse mse {
            get {
                return this.mseField;
            }
            set {
                this.mseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getHostDesc {
        
        private string getHostNameField;
        
        /// <remarks/>
        public string getHostName {
            get {
                return this.getHostNameField;
            }
            set {
                this.getHostNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getHostDescResponse {
        
        private Host hostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Host host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getServiceDesc {
        
        private string getServiceNameField;
        
        /// <remarks/>
        public string getServiceName {
            get {
                return this.getServiceNameField;
            }
            set {
                this.getServiceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getServiceDescResponse {
        
        private Service serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Service service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getDeviceDesc {
        
        private string getDeviceNameField;
        
        /// <remarks/>
        public string getDeviceName {
            get {
                return this.getDeviceNameField;
            }
            set {
                this.getDeviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getDeviceDescResponse {
        
        private Device deviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Device device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getLogicDesc {
        
        private string getLogicNameField;
        
        /// <remarks/>
        public string getLogicName {
            get {
                return this.getLogicNameField;
            }
            set {
                this.getLogicNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zonekey.com/sysmgrt/query")]
    public partial class getLogicDescResponse {
        
        private Logic logicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Logic logic {
            get {
                return this.logicField;
            }
            set {
                this.logicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getAllMsesCompletedEventHandler(object sender, getAllMsesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllMsesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllMsesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getAllMsesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getAllMsesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getMsesByShownameCompletedEventHandler(object sender, getMsesByShownameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMsesByShownameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMsesByShownameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getMsesByShownameResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getMsesByShownameResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getAllHostsCompletedEventHandler(object sender, getAllHostsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllHostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllHostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getAllHostsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getAllHostsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getAllServicesCompletedEventHandler(object sender, getAllServicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getAllServicesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getAllServicesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getAllDevicesCompletedEventHandler(object sender, getAllDevicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllDevicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllDevicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getAllDevicesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getAllDevicesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getAllLogicsCompletedEventHandler(object sender, getAllLogicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllLogicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllLogicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getAllLogicsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getAllLogicsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getServicesByTypeCompletedEventHandler(object sender, getServicesByTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServicesByTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServicesByTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getServicesByTypeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getServicesByTypeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getParentCompletedEventHandler(object sender, getParentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getParentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getParentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getParentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getParentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getBrothersCompletedEventHandler(object sender, getBrothersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBrothersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBrothersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getBrothersResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getBrothersResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getMseDescCompletedEventHandler(object sender, getMseDescCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMseDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMseDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getMseDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getMseDescResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getHostDescCompletedEventHandler(object sender, getHostDescCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHostDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHostDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getHostDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getHostDescResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getServiceDescCompletedEventHandler(object sender, getServiceDescCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServiceDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServiceDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getServiceDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getServiceDescResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getDeviceDescCompletedEventHandler(object sender, getDeviceDescCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDeviceDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDeviceDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getDeviceDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getDeviceDescResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getLogicDescCompletedEventHandler(object sender, getLogicDescCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLogicDescCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLogicDescCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getLogicDescResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getLogicDescResponse)(this.results[0]));
            }
        }
    }
}
